name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  pull_request:

env:
  NXF_ANSI_LOG: false
  NFT_VER: "0.8.4"
  NFT_WORKDIR: "~"
  NFT_DIFF: "pdiff"
  NFT_DIFF_ARGS: "--line-numbers --expand-tabs=2"

concurrency:
  group: "{% raw %}${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}{% endraw %}"
  cancel-in-progress: true

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      nf_test_files: "{% raw %}${{ steps.list.outputs.nf_test_files }}{% endraw %}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List nf-test files
        id: list
        uses: adamrtalbot/detect-nf-test-changes@v0.0.2
        with:
          head: ${{ github.sha }}
          base: origin/${{ github.base_ref }}
          include: .github/include.yml

  test:
    name: "{% raw %}${{ matrix.nf_test_files }} ${{ matrix.profile }} NF-${{ matrix.NXF_VER }}{% endraw %}"
    needs: [changes]
    if: needs.changes.outputs.nf_test_files != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        nf_test_files: ["{% raw %}${{ fromJson(needs.changes.outputs.nf_test_files) }}{% endraw %}"]
        profile:
          - "docker"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "{% raw %}${{ matrix.NXF_VER }}{% endraw %}"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: "{% raw %}${{ env.NFT_VER }}{% endraw %}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install pdiff to see diff between nf-test snapshots
        run: |
          python -m pip install --upgrade pip
          pip install pdiff

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run nf-test
        run: |
          {% raw %}nf-test test --verbose ${{ matrix.nf_test_files }} --profile "+${{ matrix.profile }}" --junitxml=test.xml --tap=test.tap{% endraw %}

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          {% raw %}batcat --decorations=always --color=always ${{ github.workspace }}/.nf-test/tests/*/meta/nextflow.log{% endraw %}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: test.xml

  confirm-pass:
    runs-on: ubuntu-latest
    needs:
      - changes
      - test
    if: always()
    steps:
      - name: All tests ok
        if: "{% raw %}${{ !contains(needs.*.result, 'failure') }}{% endraw %}"
        run: exit 0

      - name: One or more tests failed
        if: "{% raw %}${{ contains(needs.*.result, 'failure') }}{% endraw %}"
        run: exit 1

      - name: debug-print
        if: always()
        run: |
          {% raw %}echo "toJSON(needs) = ${{ toJSON(needs) }}"{% endraw %}
          {% raw %}echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"{% endraw %}
